version: '3.8'
services:
  api:
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./api/src
        target: /var/www/html
    environment:
      - MYSQL_HOST=database
      - MYSQL_DATABASE=api-db
      - MYSQL_USER=api
      - MYSQL_PASSWORD=1205
  database:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - type: volume
        source: api-db
        target: /var/lib/mysql
      - type: bind
        source: ./database/entrypoint
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./database/backup
        target: /database_backup
    environment:
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD=1712
      - MYSQL_DATABASE=api-db
      - MYSQL_USER=api
      - MYSQL_PASSWORD=1205
volumes:
  api-db: